name: Build

pool:
  vmImage: 'ubuntu-latest'

trigger:
- master

steps:
  - checkout: self

  - task: NodeTool@0
    displayName: 'Install Node'
    inputs:
      versionSpec: '12.x'

  - script: npm install
    displayName: 'Install dependencies'

  - script: npm build
    displayName: 'Build app'
